version: '3.8'
name: aws-cicd

services:
  nextjs-local:
    container_name: container
    build:  
      context: .
      dockerfile: Dockerfile.local
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules  

  nextjs-prod:
    container_name: container
    build:  
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000