name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build-and-push:
    name: build and upload image
    runs-on: self-hosted
    steps:
      - name: Pull Docker Image
      